insert into user values(101, 'atul@gmail.com', 'Atul', 'Pandey', 'admin', 'ssn101', 'atul');
insert into user values(102, 'tom@yahoo.com', 'Tom', 'Dcosta', 'user', 'ssn102', 'tom');
insert into user values(103, 'jerry@hotmail.com', 'Jerry', 'Luca', 'moderator', 'ssn103', 'jerry');
insert into orders (order_id, order_desc, user_id) values( 2001, 'order11', 101);
insert into orders (order_id, order_desc, user_id) values( 2002, 'order12', 101);
insert into orders (order_id, order_desc, user_id) values( 2003, 'order13', 101);
insert into orders (order_id, order_desc, user_id) values( 2004, 'order21', 102);
insert into orders (order_id, order_desc, user_id) values( 2005, 'order22', 102);
insert into orders (order_id, order_desc, user_id) values( 2006, 'order31', 103);